function plotModelHumanCorrelationOverTime(modelResults)
if iscell(modelResults)
    modelResults = vertcat(modelResults{:});
end

presIds = 1:300;
%% Collect data
% human
humanResults = load('data/data_occlusion_klab325v2.mat');
humanResults = humanResults.data;
humanResults = humanResults(...
    humanResults.occluded == 1 & ...
    humanResults.masked == 0, :);
subjects = unique(humanResults.subject);
idx1 = subjects(randperm(length(subjects), round(length(subjects) / 2)));
idx2 = setdiff(subjects, idx1);
humanCorrectHalfs = NaN(length(presIds), 2);
humanCorrect = NaN(length(presIds), 1);
for i = 1:size(humanCorrectHalfs,1)
    pres = presIds(i);
    relevantResults = humanResults(humanResults.pres == pres, :);
    humanCorrectHalfs(i,1) = mean(relevantResults.correct(...
        ismember(relevantResults.subject, idx1)));
    humanCorrectHalfs(i,2) = mean(relevantResults.correct(...
        ismember(relevantResults.subject, idx2)));
    humanCorrect(i) = mean(relevantResults.correct);
end
humanHumanCorrelation = corr(...
    humanCorrectHalfs(:,1), humanCorrectHalfs(:,2));
% model
modelNames = {'hop', 'RNN'};
modelTimestepNames = {...
    % hop
    'caffenet_fc7-bipolar0-libsvmccv',...
    'caffenet_fc7-bipolar0-hop_t1-libsvmccv',...
    'caffenet_fc7-bipolar0-hop_t5-libsvmccv',...
    'caffenet_fc7-bipolar0-hop_t10-libsvmccv',...
    'caffenet_fc7-bipolar0-hop_t15-libsvmccv';...
    % RNN
    'RNN_t0',...
    'RNN_t1',...
    'RNN_t2',...
    'RNN_t3',...
    'RNN_t4'...
%     % RNN
%     'fc7_orig_0occl_correct',...
%     'RNN_fc7_noRelu_t1_trainorig_correct',...
%     'RNN_fc7_noRelu_t2_trainorig_correct',...
%     'RNN_fc7_noRelu_t3_trainorig_correct',...
%     'RNN_fc7_noRelu_t4_trainorig_correct'...
    };
modelTimesteps = [zeros(size(modelTimestepNames, 1), 1), ...
    cell2mat(cellfun(@(name) timestepFromName(name), ...
    modelTimestepNames(:, 2:end), ...
    'UniformOutput', false))];
modelHumanCorrelations = NaN(size(modelTimestepNames));
for i = 1:numel(modelTimestepNames)
    modelCorrect = NaN(length(presIds), 1);
    for cri = 1:size(modelCorrect, 1);
        pres = presIds(cri);
        relevantResults = modelResults(...
            strcmp(modelTimestepNames(i), modelResults.name) & ...
            modelResults.pres == pres, :);
        assert(~isempty(relevantResults));
        modelCorrect(cri) = mean(relevantResults.correct);
    end
    modelHumanCorrelations(i) = corr(modelCorrect(:), humanCorrect(:));
end
% plot
bar(modelHumanCorrelations', ...
    'EdgeColor', 'none');
box off;
hold on;
plot(get(gca, 'xlim'), [humanHumanCorrelation humanHumanCorrelation], ...
    '-', 'Color', [1 0 0]);
ylim([-0.65 1]);
% labels
xlabels = arrayfun(@(i) ...
    strjoin(cellstr(num2str(modelTimesteps(:, i))), '\n'), ...
    1:size(modelTimesteps, 2), ...
    'UniformOutput', false);
my_xticklabels(1:length(xlabels), xlabels);
set(gca,'TickDir', 'in');
set(gca,'TickLength', [0.02 0.02]);
set(gca,'XTick', 1:length(modelTimestepNames));
for i = 1:length(modelNames)
    text(mean(get(gca, 'xlim')), mean(modelHumanCorrelations(i, :)), ...
        modelNames{i});
end
xlabel('Time step');
ylabel('Corr. with Human');
hold off;
end

function timestep = timestepFromName(classifierName)
token = regexp(classifierName, '_t([0-9]+)', 'tokens');
timestep = str2double(token{1}{1});
end
