function [filteredData, relevantRows] = filterHumanData(data)
%FILTERHUMANDATA remove training, masked and unoccluded images, use only
%data where soa = 150ms
relevantRows = ...
    data.pres <= 300 & ...
    data.masked == 0 & ...
    data.soa == .15 & ...
    data.occluded == 1;
filteredData = data(relevantRows, :);
end

