function filteredData = filterHumanData(data)
%FILTERHUMANDATA remove training, masked and unoccluded images, use only
%data where soa = 150ms
filteredData = data(...
    data.pres <= 300 & ...
    data.masked == 0 & ...
    data.soa == .15 & ...
    data.occluded == 1, :);
end

