function plotHumanPerformance(percentsVisible)
dataset = load('data/data_occlusion_klab325v2.mat');
dataset = dataset.data;
dataset = dataset(...
    dataset.pres <= 300 & ...
    dataset.masked == 0 & ...
    dataset.soa == .15, :);
subjects = unique(dataset.subject);
accuracies = zeros(length(percentsVisible), length(subjects));
visibilityMargin = (percentsVisible(2) - percentsVisible(1)) / 2;
for iPv = 1:length(percentsVisible)
    percentBlack = 100 - percentsVisible(iPv);
    for iS = 1:length(subjects)
        dataSubset = dataset(...
            dataset.subject == subjects(iS) & ...
            dataset.black >= percentBlack - visibilityMargin & ...
            dataset.black < percentBlack + visibilityMargin, :);
        accuracies(iPv, iS) = 100 * ...
            sum(dataSubset.correct) / length(dataSubset);
    end
end
meanValues = mean(accuracies, 2, 'omitnan');
standardErrorOfTheMean = std(accuracies, 0, 2, 'omitnan') / ...
    sqrt(size(accuracies, 2));
errorbar(permute(percentsVisible, [2 1]), ...
    meanValues, standardErrorOfTheMean, 'o-');
text(percentsVisible(end) + 1, meanValues(end), 'human');
